src/App.tsx
src/components/Footer/Footer.module.scss

added styles to footer & added footer to App.tsx

fix: sticky footer

---

src/components/Card/Card.module.scss
src/components/Card/Card.tsx
src/components/Card/index.ts

feat: create card

---

src/components/BurgerMenu/BurgerMenu.module.scss
src/components/BurgerMenu/BurgerMenu.tsx
src/components/Card/Card.module.scss
src/components/Card/Card.tsx
src/components/Footer/Footer.tsx
src/components/UI/Buttons/Button.module.scss
src/components/UI/Buttons/Button.tsx

fixed stlyles in button and card
added div to button so it would display as it should
corrected import for logo, changed from svg to img

fix: card and button styles, fix logo import

---

src/components/Card/Card.tsx
src/components/UI/Buttons/Button.tsx

fix: button props

---

src/components/Header/Header.module.scss

when 'favourites' icon hits 'accessories', we change min-width so everything would look nice
(optional)

fix: header media

---

src/components/UI/Buttons/Button.tsx

new logic for + - buttons, no style changes for now

chore: small fix in button logic

---

src/components/Card/Card.module.scss
src/components/Card/Card.tsx
src/components/CatalogTable/CatalogTable.module.scss
src/components/CatalogTable/CatalogTable.tsx
src/components/CatalogTable/index.ts
src/components/Footer/Footer.module.scss
src/components/UI/Dropdown/Dropdown.module.scss
src/components/UI/Dropdown/Dropdown.tsx
src/components/UI/Loader/Loader.module.scss
src/components/UI/Loader/Loader.tsx
src/components/UI/Loader/index.tsx
src/components/UI/Location/Location.module.scss
src/components/UI/Location/Location.tsx
src/pages/CatalogPage/CatalogPage.module.scss
src/pages/CatalogPage/CatalogPage.tsx
src/pages/CatalogPage/index.ts
src/styles/page.scss

CatalogPage - create component
CatalogTable - create component
Loader - create component
Footer.module.scss - remove position absolute
Dropdown.module.scss - make width adaptive
Dropdown.tsx - change isSecureContext, comment some props
Card.module.scss - make width adaptive
Card.tsx - remove hardcoded props, implement normal props
Location.tsx - fix class names syntax
Location.module.scss - correct icon position
page.scss - add paddings for all pages

feat: create catalog page

---

src/components/Card/Card.module.scss
src/components/CatalogTable/CatalogTable.module.scss
src/components/UI/Dropdown/Dropdown.module.scss
src/pages/CatalogPage/CatalogPage.module.scss
src/pages/CatalogPage/CatalogPage.tsx
src/styles/page.scss

page.scss - change height to min-height

fix: fix styles for mobile

---

src/components/Footer/Footer.module.scss
src/components/UI/Dropdown/Dropdown.module.scss
src/pages/CatalogPage/CatalogPage.module.scss
src/pages/CatalogPage/CatalogPage.tsx
src/styles/page.scss
src/utils/constants.js
src/utils/constants.ts

Footer.module.scss - add position relative
Dropdown.scss - add position relative, change option width to 100% 
CatalogPage.module.scss - add media query to dropdown container
CatalogPage - create consts and move const to separate file
page.scss - make space for content
constants.ts - add consts

fix: styles

---

src/components/Pagination/Pagination.module.scss
src/components/Pagination/Pagination.tsx
src/components/Pagination/index.ts
src/components/PaginationPage/PaginationPage.tsx
src/components/PaginationPage/index.ts
src/components/UI/Buttons/Button.tsx
src/components/UI/Dropdown/Dropdown.tsx
src/pages/CatalogPage/CatalogPage.module.scss
src/pages/CatalogPage/CatalogPage.tsx
src/types/PageSizeOption.ts
src/types/PaginationOption.ts
src/types/SortOption.ts
src/types/index.ts
src/utils/constants.ts
src/utils/helpers.ts

Pagination - create components
PaginationPage - create components
Button - add attribute disabled
CatalogPage - add Pagination component and implement only visual logic
CatalogPage.module.scss - add margin for Pagination component, change Dropdowns sizes
constants - create temporary const to use Dropdowns
Dropdown - add default value for dropdownTitle, make onItemSelected prop as optional
helpers.ts - create file for functions
PaginationOption - create type
PageSizeOption - create enum to improve Dropdowns, but it is NOT IMPLEMENTED
SortOption - create enum to improve Dropdowns, but it is NOT IMPLEMENTED

feat: create pagination component

---

src/components/Card/Card.module.scss
src/components/Card/Card.tsx
src/components/UI/Buttons/Button.module.scss

fix card styles, add hover to card and to buttons

fix: card styles, add hover

---

src/components/Pagination/Pagination.tsx
src/components/UI/Dropdown/Dropdown.tsx
src/pages/CatalogPage/CatalogPage.tsx

remove comment from pagination and catalog page
fix not to add prop ALL to searchParams

fix: fix not to add prop ALL to searchParams

---

src/App.tsx
src/Root.tsx
src/components/BurgerMenu/BurgerMenu.tsx
src/components/Card/Card.tsx
src/components/CartItem/CartItem.module.scss
src/components/CartItem/CartItem.tsx
src/components/CatalogTable/CatalogTable.tsx
src/components/Header/Header.tsx
src/components/UI/Buttons/Button.tsx
src/context/CartContext.tsx
src/index.tsx
src/pages/CartPage/CartPage.tsx
src/services/products.service.ts
src/styles/utils/variables.scss
src/types/LocalStorageCart.ts

- add cart page logic
- add cart item logic
- add logic for cart-icon to show dynamically how many items we have there with local storage
- add context, needs a bit of refactoring later
- add plus minus in cart, but with bug, fix with next commit
- add getPhoneById (we can use it when the database is ready)
- add getPhonesByIds (its for the cart and loading data from server)
- changed 'menuIsOpen' to 'isMenuOpen' since its boolean
- minor adjustment in src/styles/utils/variables.scss with fonts, i hope it wont break anything))

Feat: cartpage

---

src/components/Header/Header.module.scss
src/components/Header/Header.tsx

fixed logic for active class so it would stay on the link even after clicking on page + added a small animation
+ fixed cart count styles

style: header active link

---

src/components/Card/Card.module.scss
src/pages/CatalogPage/CatalogPage.tsx
src/services/products.service.ts
src/utils/fetchProducts.ts

CatalogPage - add pagination request, not tested
product.service, fetchProducts - add pagination function
Card.module.scss - change img size

chore: add api, fix card-img size

---

src/Root.tsx
src/components/UI/PageLocation/PageLocation.scss
src/components/UI/PageLocation/PageLocation.tsx
src/components/UI/PageLocation/index.ts
src/pages/CatalogPage/CatalogPage.tsx

feat: PageLocation component

---

src/components/Card/Card.tsx
src/components/CatalogTable/CatalogTable.tsx
src/components/Header/Header.module.scss
src/components/Header/Header.tsx
src/pages/FavouritesPage/FavouritesPage.module.scss
src/pages/FavouritesPage/FavouritesPage.tsx
src/services/products.service.ts

- add favs page
- add functionality to store favs in local storage by clicking on heart
- add counter
- adaptive design

feat: add fav page

---

src/components/Card/Card.tsx
src/components/Header/Header.tsx
src/components/SliderSmall/SliderSmall.tsx
src/components/UI/Buttons/Button.module.scss
src/context/ProductsContext.tsx
src/index.tsx
src/pages/CartPage/CartPage.module.scss
src/pages/CartPage/CartPage.tsx
src/pages/FavouritesPage/FavouritesPage.tsx
src/pages/HomePage/HomePage.module.scss
src/pages/HomePage/HomePage.tsx

- added context for favs and cart
- used context in card, sliderSmall, cartPage, header etc
- everything is working as expected
- add to cart and add to fav working as expected

feat: add context

---

src/components/UI/Buttons/Button.module.scss
src/components/UI/Dropdown/Dropdown.module.scss
src/components/UI/Dropdown/Dropdown.tsx
src/pages/CatalogPage/CatalogPage.tsx
src/services/products.service.ts
src/types/PhonesWithPagination.ts
src/types/index.ts

create pagination logic, but can't check because get only array in responce, without whole items count
fix dropdown options - make the whole option space clickable
fix button stiles - after clicking the button on hover has an active color

feat: create pagination function

---

src/pages/CatalogPage/CatalogPage.tsx
src/services/products.service.ts
src/types/SearchParams.ts
src/utils/helpers.ts

fix: change phones.length to itemsCount
serveces - add test function
helper, types serchParams - add ability to use arrays is serch params

fix: change phones.length to itemsCount

---

src/components/UI/PageLocation/PageLocation.scss
src/components/UI/PageLocation/PageLocation.tsx
src/pages/ItemCardPage/ItemCardPage.module.scss
src/pages/ItemCardPage/ItemCardPage.tsx

- added breadcrumbs to Item Page
- added new logic to breadcrumbs

fix: update breadcrumbs

---

src/context/ProductsContext.tsx
src/pages/CartPage/CartPage.module.scss
src/pages/CartPage/CartPage.tsx

fix: empty cart

---

src/components/CartItem/CartItem.tsx
src/context/ProductsContext.tsx
src/pages/CartPage/CartPage.module.scss
src/pages/CartPage/CartPage.tsx

Reverts fe-jul23-team6/product_catalog#73

Revert "chore: functions"

---

src/pages/HomePage/HomePage.module.scss
src/pages/HomePage/HomePage.tsx

minor hotfixes to HomePage connected to chevron, Link etc.

fix: minor hotfixes to HomePage

---

src/components/Footer/Footer.module.scss
src/components/Footer/Footer.tsx
src/components/Modal/Modal.module.scss
src/components/Modal/Modal.tsx
src/components/Modal/index.tsx

feat:modal

---

src/components/Footer/Footer.module.scss
src/pages/HomePage/HomePage.tsx
src/pages/ItemCardPage/ItemCardPage.tsx
src/services/products.service.ts

adds small slider to ItemCardPage

feat: add small slider to ItemCardPage

---

src/pages/ItemCardPage/ItemCardPage.tsx
src/services/products.service.ts

filtering recommended products for the slider on ItemCardPage replaced with fetching them from server

fix: add fetching recommended from server

---

src/components/Footer/Footer.module.scss
src/components/SliderSmall/SliderSmall.module.scss

back-to-top is always on top now

fix: back-to-top always on top

---

src/pages/AccessoriesPage/AccessoriesPage.module.scss
src/pages/AccessoriesPage/AccessoriesPage.tsx
src/pages/TabletsPage/TabletsPage.module.scss
src/pages/TabletsPage/TabletsPage.tsx

add tablets and accessories page

feat: add tablets and accessories pages

---

src/context/ProductsContext.tsx
src/pages/CartPage/CartPage.tsx

- finally fixed the problem with phones not loading in the cart
- FINALLY FIXED phantom phones in cart bug
- finally fixed counter in header
peremoga🎉

fix: cart count

---

src/components/Footer/Footer.tsx
src/hooks/index.tsx
src/pages/HomePage/HomePage.tsx

chore: hooks export

---

src/Root.tsx
src/components/Card/Card.tsx
src/components/CartItem/CartItem.tsx
src/components/UI/Breadcrumbs/Breadcrumbs.tsx
src/context/ProductsContext.tsx
src/pages/AccessoriesPage/AccessoriesPage.tsx
src/pages/CatalogPage/CatalogPage.tsx
src/pages/ContactsPage/ContactsPage.tsx
src/pages/FavouritesPage/FavouritesPage.tsx
src/pages/ItemCardPage/ItemCardPage.tsx
src/pages/TabletsPage/TabletsPage.tsx

update routing and product navigation
update Breadcrumbs

fix: update product pagas navigation

---

src/components/Card/Card.tsx
src/pages/ItemCardPage/ItemCardPage.tsx

fix link in Card and add scroll to top

fix: link in card and scroll in ItemCardPage
